### ISSUE TITLE
Brand packet changed

### ISSUE THREAD

**Issue by ShayBox** [theminecoder/ServerBrand#1]
The brand packet changed to `minecraft:brand`, so some sort of protocol version check to change the channel name for the connecting user (to support multi-version servers)

**Comment by theminecoder** [comment]
There is already support for this within the code. https://github.com/theminecoder/ServerBrand/blob/master/src/main/java/me/theminecoder/minecraft/serverbrand/ServerBrandBungeeCord.java#L82 https://github.com/theminecoder/ServerBrand/blob/master/src/main/java/me/theminecoder/minecraft/serverbrand/ServerBrandSpigot.java#L27
